---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consul-kv-jolie
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: consul-kv-jolie
    spec:
      containers:
        - image: "dm848/srv-consul-kv-jolie:v1"
          imagePullPolicy: Always
          name: consul-kv-jolie
          ports:
            - containerPort: 8888
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: consul-kv-jolie
  namespace: "default"
  labels:
    app: consul-kv-jolie
spec:
  ports:
  - protocol: "TCP"
    port: 8888
    targetPort: 8888
  selector:
    app: consul-kv-jolie
  type: "ClusterIP"
